### ISSUE TITLE
Weird crash upon putting a book inside the Enchanting Table's GUI

### ISSUE THREAD

**Issue by ShinryuAspect** [Fuzss/enchantinginfuser-fabric#3]
I'm experiencing a weird crash just as soon as I place a book inside the Enchanting Table's slot and it pops me to the Multiplayer screen with that wonderful screen saying "Connections Lost" and the button that returns me to the server list, even tho I'm playing in single player.
It's worth noting that upon rejoining the world, the book stays visually rendered on top of the table, but as soon as I open the GUI, it crashes again the same way. It only seem to happen with books, as I've tried with both tools and armor and it doesn't crash (unless not as soon as I place it in the slot, haven't got any deeper, just testing).

```
[20:41:56] [Netty Local Client IO #2/ERROR]: Encountered exception while handling in channel with name "enchantinginfuser:play/0"
java.lang.IllegalArgumentException: initialArraySize cannot be negative but was: -56
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.14) ~[?:?]
	at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:40) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:178) ~[guava-31.0.1-jre.jar:?]
	at fuzs.enchantinginfuser.network.message.S2CCompatibleEnchantsMessage.read(S2CCompatibleEnchantsMessage.java:41) ~[EnchantingInfuser-v3.1.0-1.18.1-Fabric.jar:?]
	at fuzs.puzzleslib.network.NetworkHandler.lambda$register$0(NetworkHandler.java:64) ~[PuzzlesLib-v3.1.3-1.18.1-Fabric.jar:?]
	at fuzs.puzzleslib.util.PuzzlesUtil.make(PuzzlesUtil.java:23) ~[PuzzlesLib-v3.1.3-1.18.1-Fabric.jar:?]
	at fuzs.puzzleslib.network.NetworkHandler.lambda$register$1(NetworkHandler.java:64) ~[PuzzlesLib-v3.1.3-1.18.1-Fabric.jar:?]
	at fuzs.puzzleslib.proxy.ClientProxy.lambda$registerClientReceiver$1(ClientProxy.java:31) ~[PuzzlesLib-v3.1.3-1.18.1-Fabric.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.0.18+3ac43d9565-52b11e5e3e3e03a2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.0.18+3ac43d9565-52b11e5e3e3e03a2.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) ~[fabric-networking-api-v1-1.0.18+3ac43d9565-52b11e5e3e3e03a2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.18+3ac43d9565-52b11e5e3e3e03a2.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$ccg000$handleCustomPayload(ClientPlayNetworkHandler:2429) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:60) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:8) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:163) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:150) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:53) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
I'm also attaching the log itself so you can check the mods I have. It may be due to the amount of enchantments added from other mods? I don't think think it's an incompatibility with a mod, it may just be that the amount of enchantments exceeds the max amount allowed to be "visually rendered" in the GUI or something along the line.

EDIT: I forgot to mention it, but it crashes with both the Enchant Infuser and the Advanced version. Also, as I supposed, it correcly lets me put tools and armor inside the slot without crashing, even those from mods (I've tried with the full Netherite tool and armor set and armors and tools from both BetterNether and the Minecraft Dungeons Weapons/Armors and it didn't crash).

[latest.log](https://github.com/Fuzss/enchantinginfuser-fabric/files/7824341/latest.log)

**Comment by Fuzss** [comment]
Thanks for the report, fixed in latest version on Curse.
